version: "3.8"

services:
  server1:
    build: ./server1
    ports:
      - "3001:3001"
    volumes:
      - ./server1:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    environment:
      PORT: 3001

  server2:
    build: ./server2
    ports:
      - "3002:3002"
    volumes:
      - ./server2:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    environment:
      PORT: 3002
